#!/usr/bin/python
from test import TestSuite
suite = TestSuite("data/minimal.tc")
suite.addSignal("s_enable_ocram", 1, alias="ocram", default=False)
suite.addSignal("s_reset", 1, alias="reset", default=True)
suite.addSignal("s_mem_in.rddata", 32, alias="rddata", default=0)
suite.addSignal("s_mem_in.busy", 1, alias="busy", default=False)
suite.addSignal("a_mem_out.address", 21, alias="addr", default="---------------------")
suite.addSignal("a_mem_out.rd", 1, alias="rd", default="-")
suite.addSignal("a_mem_out.wr", 1, alias="wr", default="-")
suite.addSignal("a_mem_out.byteena", 4, alias="byteena", default="----")
suite.addSignal("a_mem_out.wrdata", 32, alias="wrdata", default="--------------------------------")
suite.test(0, )
suite.test(1, rd=False, wr=False)
suite.test(2, rd=False, wr=False)
suite.test(3, rd=False, wr=False)
suite.test(4, rd=False, wr=False)
suite.test(5, rd=True, wr=False, addr="000000000000000000100")
suite.test(6, rd=False, wr=False)
suite.test(7, rd=False, wr=False)
suite.test(8, rd=False, wrdata="00000000000000000000000000000000", addr="000000000000000001000", wr=True, byteena="1111")
suite.test(9, rd=False, wr=False)
suite.test(10, rd=False, wr=False)
